version: 2.1

orbs:
    python: circleci/python@2.1.1
    codecov: codecov/codecov@3.2.3

jobs:
    prepare_environment:
        docker:
        - image: cimg/python:3.10.7 # Includes Poetry 1.2.0
        resource_class: large
        steps:
        - checkout
        - restore_cache:
            keys:
            - cache_key-pyenvtox-{{ checksum ".circleci/config.yml" }}
        - run: pip install tox
        - run: |
            pyenv install -s 3.8.0
            pyenv install -s 3.9.13
            pyenv install -s 3.10.6
            pyenv local 3.8.0 3.9.13 3.10.6
        - save_cache:
            paths:
            - ~/.pyenv/versions
            - .python-version
            key: cache_key-pyenvtox-{{ checksum ".circleci/config.yml" }}

    run_tests:
        docker:
        - image: cimg/python:3.10.7 # Includes Poetry 1.2.0
        resource_class: large
        steps:
        - checkout
        - restore_cache:
            keys:
            - cache_key-pyenvtox-{{ checksum ".circleci/config.yml" }}
        - python/install-packages:
            pkg-manager: poetry
            args: --without dev
        - run: |
            eval "$(pyenv init -)"
            pyenv shell 3.10.7
            pyenv exec tox
            pyenv shell --unset
        - codecov/upload
        # - store_artifacts:
        #     path: htmlcov
        - store_test_results:
            path: .tox/test_results
        # - store_artifacts:
        #     path: .tox/test_results
workflows:
    tests:
        jobs:
        - prepare_environment
        - run_tests:
            requires:
            - prepare_environment
